apiVersion: v1
kind: ConfigMap
metadata:
  name: vmagent-config
data:
  scrape.yaml: |
    global:
      scrape_interval: 30s

    scrape_configs:
      - job_name: openmetrics-exporter
        static_configs:
          - targets: ["localhost:9100"]

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: ome-vmagent
  labels:
    app: ome-vmagent
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: ome-vmagent
  template:
    metadata:
      labels:
        app: ome-vmagent
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      containers:
      - name: openmetrics-exporter
        image: last9.jfrog.io/last9-openmetrics-exporter-docker/openmetrics-exporter:latest
        command: ["/app/l9watcher"]
        args: ["-a", "run openmetrics", "-c", "/var/ome/json-maker.sh", "-d", "true", "-f", "60", "-v", "true"]
        ports:
        - containerPort: 9100
        volumeMounts:
        - name: exporters
          mountPath: /ome
        envFrom:
        - secretRef:
            name: ome-env
        imagePullPolicy: Always

      - name: vmagent
        image: victoriametrics/vmagent:v1.76.1
        args:
          - "--promscrape.config=/etc/vmagent/scrape.yaml"
          # - "--remoteWrite.url=https://<remote write reciever>/api/v1/write"
        ports:
        - name: web
          containerPort: 9090
        volumeMounts:
        - name: vmagent-config
          mountPath: /etc/vmagent/
      restartPolicy: Always

      volumes:
      - name: vmagent-config
        configMap:
          name: vmagent-config

      - name: exporters
        configMap:
          name: exporters
