apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmetrics-exporter-deployment
  labels:
    app: openmetrics-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openmetrics-exporter
  template:
    metadata:
      labels:
        app: openmetrics-exporter
    spec:
      containers:
      - name: openmetrics-exporter
        image: last9.jfrog.io/last9-openmetrics-exporter-docker/openmetrics-exporter:latest
        command: ["/app/l9watcher"]
        args: ["-a", "run openmetrics", "-c", "/var/ome/json-maker.sh", "-d", "true", "-f", "60", "-v", "true"]
        ports:
        - containerPort: 9100
        volumeMounts:
        - name: exporters
          mountPath: /ome
        envFrom:
        - secretRef:
            name: ome-env
        imagePullPolicy: Always
      volumes:
      - name: exporters
        configMap:
          name: exporters

