name: Release

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create a release
        id: create_tag
        uses: rymndhng/release-on-push-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bump_version_scheme: patch

      - name: Get HCL files to release
        id: find_files
        env:
          RELEASE_TYPE: "${{ contains(github.ref, 'release-') && 'major' || 'patch' }}"
        run: |
          files=$(.github/scripts/generate_assets.sh $RELEASE_TYPE | xargs)
          echo "::set-output name=hcl_files::$files"

      - name: test
        run: echo ${{ steps.find_files.outputs.hcl_files }}

      - name: Upload release assets
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.create_tag.outputs.tag_name }}
          allow_override: true
          gzip: false
          files: >
            ${{ steps.find_files.outputs.hcl_files }}
            docker-compose.yaml:sample/docker-compose.yaml
            scrape.yaml:sample/scrape.yaml
            generate_ome_data.sh:sample/k8s/generate_ome_data.sh
            ome.yaml:sample/k8s/ome.yaml
            ome-vmagent.yaml:sample/k8s/ome-vmagent.yaml
