name: Test

on: [push]

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: "1.16"

    - name: Get hclfmt
      run: GO111MODULE=on go get github.com/hashicorp/hcl/v2/cmd/hclfmt@v2.14.1

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Run tests
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      run: cd tests && make test
